// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCAWeb.Service.Ativos.Data;

namespace SCAWeb.Service.Ativos.Migrations
{
    [DbContext(typeof(AtivosContext))]
    [Migration("20201025143002_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SCAWeb.Service.Ativos.Entities.AgendaManutencaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data_atualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("data_manutencao")
                        .HasColumnType("datetime");

                    b.Property<Guid>("id_insumo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("status_agenda")
                        .HasColumnType("int");

                    b.Property<int>("tipo_manutencao")
                        .HasColumnType("int");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgendaManutencao");
                });

            modelBuilder.Entity("SCAWeb.Service.Ativos.Entities.FornecedorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cnpj_fornecedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data_atualizacao")
                        .HasColumnType("datetime");

                    b.Property<string>("nome_fantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("razao_social")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("SCAWeb.Service.Ativos.Entities.InsumoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data_aquisicao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("data_atualizacao")
                        .HasColumnType("datetime");

                    b.Property<string>("descricao_insumo")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("id_fornec_insumo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_tipo_insumo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("qtd_dias_manut_prev")
                        .HasColumnType("int");

                    b.Property<int>("status_insumo")
                        .HasColumnType("int");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("SCAWeb.Service.Ativos.Entities.ManutencaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data_fim")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("data_inicio")
                        .HasColumnType("datetime");

                    b.Property<string>("descricao_manutencao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("id_insumo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("status_manutencao")
                        .HasColumnType("int");

                    b.Property<int>("tipo_manutencao")
                        .HasColumnType("int");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manutencao");
                });

            modelBuilder.Entity("SCAWeb.Service.Ativos.Entities.TipoInsumoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data_atualizacao")
                        .HasColumnType("datetime");

                    b.Property<string>("descricao_tp_insumo")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoInsumo");
                });
#pragma warning restore 612, 618
        }
    }
}
